### ISSUE TITLE
Assinatura de pdfs

### ISSUE THREAD

**Issue by cmmp** [demoiselle/signer#100]
Olá pessoal,

É possível assinar pdfs com esse projeto?

Estou tentando assinar pdfs com e-cpf e já usei duas bibliotecas: iText e o pdfbox do apache.

Ainda não consegui fazer meu pdf ser validado pelo Adobe Reader, apesar de já ter importado os certificados raiz do ICP no Adobe.

Alguma dica?

**Comment by esaito** [comment]
O Demoiselle-Signer pode dar suporte a essa implementação. O pdfbox pode ser uma biblioteca acessória para acoplar a assinatura gerada pelo Signer no PDF.
O SERPRO está desenvolvendo um Assinador para uso em Desktop que trará essa funcionalidade.

**Comment by cmmp** [comment]
Legal. Eu acabei conseguindo tanto com o iText como pdfbox. Mas seria interessante ter uma implementação de referência do SERPRO mesmo.

**Comment by esaito** [comment]
https://serpro.gov.br/links-fixos-superiores/assinador-digital/assinador-serpro

**Comment by cmmp** [comment]
Muito legal @esaito ! O código já está aqui no demoiselle?

**Comment by cmmp** [comment]
PS: @esaito,  O Windows defender está detectando uma ameaça no instalador.

**Comment by esaito** [comment]
Por enquanto o codigo é interno ao SERPRO. A questão do windows é complicada, ele por si só é uma ameaça a segurança. Mas poderia detalhar o problema?

**Comment by edilinux** [comment]
Olá pessoal, só revivendo o assunto, é possível fazer co-assinatura com PDF?
Algum exemplo de como acoplar um arquivo pkcs7 no PDF?
Obrigado.

**Comment by esaito** [comment]
Sim. Para co-assinatura, basta ter mais de uma assinatura no arquivo. a contra-assinatura nunca testei.
O [](http://www.serpro.gov.br/assinador-digital) não atende sua necessidade?

**Comment by edilinux** [comment]
Atende ele é ótimo! Mas eu estou fazendo um jar que precisa rodar sem interface gráfica, e também a questão do carimbo da assinatura no meu caso preciso que fique parametrizável e customizável.
Eu consegui assinar e co-assinar arquivos sem problemas mas estou apanhando nos PDFs tanto na hora de inserir o arquivo p7s no PDF, quanto pra recuperar o p7s de dentro do PDF...

**Comment by edilinux** [comment]
Teria algum exemplo pra eu seguir? obrigado.
