### ISSUE TITLE
Assinador do SEI! e do SERPRO utilizam o Demoiselle Signer? 

### ISSUE THREAD

**Issue by bcfreitas** [demoiselle/signer#122]
Olá,

Me chamo Bruno Freitas, sou servidor da UFPE, estou fazendo parte de uma comissão de implantação de Processo Eletrônico na instituição.

Estava estudando sobre como o SEI! (Sistema Eletrônico de Informações - TRF4) faz assinatura com certificado digital, e cheguei ao componente Demoiselle Signer.

Gostaria de confirmar se tanto o SEI! como o Assinador do Serpro utilizam o componente Demoiselle Signer em suas implementações.

Sabem informar?

Estou tentando obter esta confirmação para levar à próxima reunião da comissão do Processo Eletrônico da UFPE.

Agradeço antecipadamente,

Atenciosamente,

Bruno Chaves de Freitas
Analista de Tecnologia
Núcleo de Tecnologia da UFPE

**Comment by joserenecampa** [comment]
Olá Bruno!

O [Assinador SERPRO](https://www.serpro.gov.br/links-fixos-superiores/assinador-digital/assinador-serpro) utiliza o Demoiselle Signer. Não tenho informações a respeito do SEI!.

Abraços,

René

**Comment by estevaocm** [comment]
Recentemente observei em uma captura de tela do SEI de uma versão cuja data desconheço que era construido baseado no Demoiselle Certificate, que foi uma versão anterior do Demoiselle Signer. Se não me engano, no SEI ainda estava como applet, mas o suporte para a plataforma Applet foi descontinuado por todos os browsers e hoje se usa a plataforma Java Web Start.

**Comment by estevaocm** [comment]
Por sinal, a minha equipe aqui na Regional Recife do Serpro está desenvolvendo um sistema genérico de gestão de assinatura digital de documentos PDF (facilmente ampliável para qualquer arquivo) em cima do Demoiselle Signer. Se a UFPE quiser contratar os serviços do Serpro, estamos à disposição. =)

**Comment by bcfreitas** [comment]
Obrigado pelas informações.

A situação aqui na UFPE é a seguinte, estamos implantando o SIPAC (proveniente da UFRN), e pretendemos customizar o módulo de Protocolo para permitir assinatura digital, tanto nos documentos que o próprio SIPAC gera (dinamicamente a partir de consulta em banco de dados e exibição na tela) quanto em documentos anexados por usuário (DOC, PDF, ODP, etc).

@estevaocm , em princípio a solução que descreveste não nos atenderia completamente. 

Estamos no momento entre dois caminhos: 
(a) utilizar o demoiselle signer para esta customização;
(b) adquirir e utilizar a solução LACUNA docs (https://docs.lacunasoftware.com/pt-br/index.html) na customização.

Mas ainda estamos tentando entender melhor o que o demoiselle oferece para decidir. O demoiselle signer só permite a assinatura digital com arquivo auxiliar p7s (dettached), ou também insere a assinatura diretamente em arquivos (como o Libreoffice faz, inserindo o hash da assinatura diretamente nos arquivos DOC, ODP, PDF)?  @esaito se puder ajudar, agradeço.

**Comment by bcfreitas** [comment]
Fechei a issue porque já estava saindo do objetivo inicial, abri outra.

**Comment by fabiomazga** [comment]
Olá! Estou desenvolvendo uma API em Java para o SISCOMEX. Estou tendo problema em autenticar o  X-CSRF-Token não é válido. Alguém pode me ajudar? Grato.
