### ISSUE TITLE
O Signer permite assinatura direta em arquivos (ODP, PDF, DOC)?

### ISSUE THREAD

**Issue by bcfreitas** [demoiselle/signer#132]
A situação aqui na UFPE é a seguinte, estamos implantando o SIPAC (proveniente da UFRN), e pretendemos customizar o módulo de Protocolo para permitir assinatura digital, tanto nos documentos que o próprio SIPAC gera (dinamicamente a partir de consulta em banco de dados e exibição na tela) quanto em documentos anexados por usuário (DOC, PDF, ODP, etc).

@estevaocm , em princípio a solução que descreveste não nos atenderia completamente.

Estamos no momento entre dois caminhos:
(a) utilizar o demoiselle signer para esta customização;
(b) adquirir e utilizar a solução LACUNA docs (https://docs.lacunasoftware.com/pt-br/index.html) na customização.

Mas ainda estamos tentando entender melhor o que o demoiselle oferece para decidir. O demoiselle signer só permite a assinatura digital com arquivo auxiliar p7s (dettached), ou também insere a assinatura diretamente em arquivos (como o Libreoffice faz, inserindo o hash da assinatura diretamente nos arquivos DOC, ODP, PDF)? @esaito se puder ajudar, agradeço.

**Comment by esaito** [comment]
Então, o Demoiselle-Signer gera assinaturas p7s (CADES) que podem ser inseridas em arquivos que usam esse tipo de formato, como o PDF por exemplo . Se os outros arquivos também usam CADES como formato de assinatura é provável que tenha uma forma de embutir. Mas essas funcionalidade não são exatamente do Signer, pois o papel do Signer é gerar a assinatura. A solução que a equipe do  Estevão (@estevaocm) está desenvolvendo faz isso com o PDF (embutir diretamente), não sei se farão para outros formatos.  O Assinador SERPRO (https://www.serpro.gov.br/assinador-digital) também faz assinatura embutida em PDF.

**Comment by joserenecampa** [comment]
O Demoiselle Signer foi implementado para ser aderente às assinaturas no padrão brasileiro de assinatura digital, o PBAD. Aconselho a leitura do documento que é a base do trabalho do Demoiselle Signer:
http://www.iti.gov.br/images/repositorio/legislacao/documentos-principais/DOC-ICP-15_-_Versao_3.0_VISAO_GERAL_SOBRE_ASSIN_DIG_NA_ICP-BRASIL_25-08-2015.pdf

Pelo que pude perceber pela documentação do LACUNA Software, este adota os padrões Cades, Pades e Xades. O Demoiselle Signer implementa, atualmente, apenas o padrão Cades, mas é importante entender o modelo para saber se as ferramentas são aderentes ao PBAD. Será que um arquivo DOC, XLS ou ODT conseguem suportar uma assinatura "atachada" nesses padrões? Será que as ferramentas que adotam esses documentos (Word, OpenOffice, Excel, etc) têm padrões similares ou extendidos? 
Por exemplo, o formato de assinatura digital PADES (PDF), que é uma extensão do Cades, foi adotado pelo PBAD a pouco tempo, ou seja, não era aderente ao modelo brasileiro até pouco tempo atrás.

**Comment by estevaocm** [comment]
@bcfreitas, o Lacuna faz assinatura embutida de PDF, DOC, ODP etc.? Não encontrei essa informação no site deles.

Eu sei que existe API Java de Open Document que poderia fazer esse tipo de operação, mas não sei se a compatibilidade com formatos Microsoft presta.

Na realidade, não vejo muito sentido técnico nem prático em assinar documentos editáveis. Me parece que faz mais sentido exportá-los pra PDF e então assiná-los. Qual seria a vantagem de manter tal documento ODT, ODP etc.?

**Comment by bcfreitas** [comment]
Pessoal agradeço pelas respostas. Li o DOC_ICP_15 sugerido e constatei que realmente trata a assinatura e o conteúdo como objetos distintos que precisam ser mapeados. 

Sobre o sentido de assinar documentos editáveis (ODP, ODT), penso que seria útil também pois o fato de ser editável não obstaria a assinatura, já que se outra pessoa editar (aproveitando o documento para outros fins) perde a assinatura. De toda forma ainda não há uma demanda específica disto na UFPE, foi só uma curiosidade. 

Agradeço novamente pela atenção.
