### ISSUE TITLE
Dividir o procedimento de assinatura em duas etapas

### ISSUE THREAD

**Issue by joserenecampa** [demoiselle/signer#139]
Vamos discutir a possibilidade de separar o procedimento de assinatura em duas etapas. Embora o componente possua a funcionalidade de assinar a partir do resumo (hash), poderíamos adotar esse procedimento como padrão.
Atualmente a assinatura com a presença dos dados originais é realizada completamente no dispositivo criptográfico, uma vez que o `provedor` será o mesmo para o algoritmo de resumo e para o algoritmo de criptografia. Após algumas experiências com o Demoiselle Signer, pudemos detectar que existe alguns `provedores` criptográficos que possuem algumas limitações nos algoritmos de resumo e nestes casos poderíamos realizar com segurança esse algoritmo utilizando provedores por software, como o BouncyCastle ou até mesmo nativamente pela JVM. Pode ser que vários problemas de compatibilidade com provedores seja resolvido com essa abordagem.

**Comment by denisfalqueto** [comment]
Olá, gostaria de dizer que concordo com essa proposta. Também gostaria de colocar à disposição uma biblioteca que venho desenvolvendo para acesso direto a dispositivos via PKCS11. Ela encontra-se em https://gitlab.com/denisfalqueto/EasyPkcs11. Ela já possui uma integração como BouncyCastle, fornecendo um builder de ContentSigner que pode integrar-se ao restante do BouncyCastle apenas para efetuar a assinatura no dispositio. Estou à disposição para mais informações.

**Comment by esaito** [comment]
Lançada primeira versão SNAPSHOT: 4.1.0-SNAPSHOT 
Nesta release é possível ser gerados primeiros os atributos assinados e na segunda passagem os não assinados.
Por enquanto para CAdES e PAdES, na próxima interação faremos com XML.
Na seguinte podemos ter a sugestão de enviar sempre o hash calculado para geração de assinaturas
