### ISSUE TITLE
Rever mecanismo de assinatura com certificados de homologação

### ISSUE THREAD

**Issue by joserenecampa** [demoiselle/signer#141]

**Comment by vinydanylo** [comment]
Boa noite senhores! Estou com uma dúvida do porquê que foi adicionada essa validação 

`if (this.certificateChain.length < 3) {
	throw new SignerException(cadesMessagesBundle.getString("error.no.ca", this.certificate.getIssuerDN()));
}`

no arquivo https://github.com/demoiselle/signer/commit/ee2d923d1f40e5d1144db69a1dd9e1f38cbed9c3#diff-119e6461d1f7b09f149fc62c4a9ec61e

Isso está me bloqueando quando tento assinar um documento. Talvez se eu entender o porquê desta validação, eu possa solucionar o problema.

Este é o meu trecho de código:

`    public static byte[] signDetachedFileFromFilePath(Certificate cert, PrivateKey pKey, String pdfFilePath)
            throws IOException {

        byte[] content = Files.readAllBytes(Paths.get(pdfFilePath));
        PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();
        signer.setCertificates(new Certificate[] { cert });
        signer.setPrivateKey(pKey);
        signer.setSignaturePolicy(Policies.AD_RA_CADES_1_0);

        return signer.doDetachedSign(content);
    }`

Obrigado pela atençao e tenha um ótimo dia!

**Comment by esaito** [comment]
Há dois erros no código: 
signer.setCertificates(new Certificate[] { cert });
Você deve passar a um array com a cadeia toda do certificado não somente do assinante.

signer.setSignaturePolicy(Policies.AD_RA_CADES_1_0);
Ainda não há suporte para essa política, atualmente só RB, RT e RV, além disso a versão atual é a 2_3

Consulte o codigo de teste e exemplo:

[https://github.com/demoiselle/signer/blob/master/policy-impl-cades/src/test/java/org/demoiselle/signer/policy/impl/cades/pkcs7/impl/CAdESSignerTest.java
](https://github.com/demoiselle/signer/blob/master/policy-impl-cades/src/test/java/org/demoiselle/signer/policy/impl/cades/pkcs7/impl/CAdESSignerTest.java
)
