### ISSUE TITLE
Gestão das ACs

### ISSUE THREAD

**Issue by joserenecampa** [demoiselle/signer#15]
Existe a necessidade de discutir a maneira como o componente se comporta ao lidar com cadeia de autoridades confiáveis.

- É responsabilidade do componente ficar atualizado? Pode ser um ponto único de manutenção em caso de atualizações mas também pode ser gargalo para projetos.

- O componente pode utilizar o campo "Authority Information Access" caso exista? Não é um campo obrigatório, mas a maioria das ACs da ICP-Brasil geram certificados com esse campo preenchido. Referência: https://tools.ietf.org/html/rfc5280#section-4.2.2.1. OBS: É uma informação On-Line, acesso semelhante às LCRs.

- É possível manter um arquivo "JAR" assinado e on-line que implementasse a mesma funcionalidade do demoiselle-ca-icpbrasil.jar mas de forma a consumir o arquivo "ACcompactados.zip" do ITI. As applets ou JavaWebStarts que utilizarem este JAR on-line, deverão apontá-lo em seus descritores. JavaWebStart no arquivo JNLP e a Applet na tag "<object applet" do arquivo HTML.

**Comment by joserenecampa** [comment]
Existe a necessidade de discutir a maneira como o componente se comporta ao lidar com cadeia de autoridades confiáveis.

- É responsabilidade do componente ficar atualizado? Pode ser um ponto único de manutenção em caso de atualizações mas também pode ser gargalo para projetos.

- O componente pode utilizar o campo "Authority Information Access" caso exista? Não é um campo obrigatório, mas a maioria das ACs da ICP-Brasil geram certificados com esse campo preenchido. Referência: https://tools.ietf.org/html/rfc5280#section-4.2.2.1. OBS: É uma informação On-Line, acesso semelhante às LCRs.

- É possível manter um arquivo "JAR" assinado e on-line que implementasse a mesma funcionalidade do demoiselle-ca-icpbrasil.jar mas de forma a consumir o arquivo "ACcompactados.zip" do ITI. As applets ou JavaWebStarts que utilizarem este JAR on-line, deverão apontá-lo em seus descritores. JavaWebStart no arquivo JNLP e a Applet na tag "<object applet" do arquivo HTML.

**Comment by juliancesar** [comment]
https://github.com/demoiselle/signer/wiki/Prioridade-de-Providers
