### ISSUE TITLE
Estou com problema na utilização da biblioteca de assinatura CADES quando vai tentar resgatar as CAs...

### ISSUE THREAD

**Issue by leoclaro** [demoiselle/signer#151]
Boa tarde a todos,
gostei muito da biblioteca da equipe, parabéns a todos.

Estou apenas com uma dificuldade para assinar 1 documento utilizando CAdES da biblioteca "Demoiselle Signer CADES". Utilizei a classe de exemplo "CAdESSignerTest", até quando a parte que carrega o certificado A1 funciona perfeitamente, porém quando vai efetuar a assinatura na linha "byte[] signature = signer.doDetachedSign(fileToSign);" ocorre a exceção: "org.demoiselle.signer.policy.impl.cades.SignerException: Nao foi possivel resgatar as CAs do provedor CN=AC Certisign RFB G5, OU=Secretaria da Receita Federal do Brasil - RFB, O=ICP-Brasil, C=BR
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:532)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:497)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doDetachedSign(CAdESSigner.java:784)
	at br.com.recivil.domain.Teste.testSignDetached(Teste.java:93)"

Tentei utilizando o PFX A1 da empresa, e também tentei ele no formato JKS, ambos da erro ao tentar resgatar as CAs. Eu utilizo esse certificado A1 em outra aplicação em uma consolidação de webservice ws-security e funciona corretamente.

**Comment by esaito** [comment]
Boa tarde, 
Vc clonou o projeto Git e está executando o teste unitário "CAdESSignerTest" ?
Ou está usando outro projeto e só usou o exemplo?
Caso seja em outro projeto certifique-se que está com a dependência:

                 <dependency>
			<groupId>org.demoiselle.signer</groupId>
			<artifactId>chain-icp-brasil</artifactId>
                        <version> 3.2.7 </version>
		</dependency>

**Comment by leoclaro** [comment]
Em vez de clonar, eu baixei o compactado todo, e abri no netbeans como existente maven project, depois eu abri o modulo "Demoiselle Signer CADES", e dentro dele criei um pacote para testar, e uma classe "Teste.java" baseado na classe existente de teste "CAdESSignerTest", alterando para usar o A1. Ai eu coloquei para executar a classe minha "Teste.java" como principal para testar assinatura.

**Comment by esaito** [comment]
Então verifique mesmo as dependências do POM.XML, do projeto. Inclusive o escopo, no exemplo está como TEST, pois só é usado pelo JUnit.

**Comment by leoclaro** [comment]
Entendi, eu olhei o arquivo POM e possui o artefato "chain-icp-brasil", tirei um print de como está o projeto, eu apenas abri o projeto "Demoiselle Signer CADES", e criei essa classe Teste.java baseado na de teste unitario modificando para funcionar com A1 meu.

![image](https://user-images.githubusercontent.com/3679281/39721871-30b48a88-5217-11e8-93fe-7211b2c918cf.png)

![image](https://user-images.githubusercontent.com/3679281/39721898-4a030924-5217-11e8-8585-e5221d20858f.png)

![image](https://user-images.githubusercontent.com/3679281/39721908-51587f88-5217-11e8-9f69-2861bfe1fe91.png)

**Comment by esaito** [comment]
Obrigado!
