### ISSUE TITLE
Por quê o Demoiselle Signer não está no Portal do Software Público Brasileiro?

### ISSUE THREAD

**Issue by bcfreitas** [demoiselle/signer#153]
Localizei o Demoiselle Infra, mas não o Demoiselle Signer.

Por quê ainda não está no Portal? Tem alguns requisitos legais que ainda não são atendidos pelo projeto?

Agradeço!

**Comment by fgsl** [comment]
@bcfreitas, pergunte aqui: https://esic.cgu.gov.br/sistema/site/index.aspx
