### ISSUE TITLE
Validação da assinatura no Verificador do iti

### ISSUE THREAD

**Issue by EngBruno** [demoiselle/signer#162]
Estou assinando documentos no formato CADES, a assinatura e a verificação esta funcionado normalmente. Faço as verificações nas seguintes plataformas:

1. bryclound verificação
2. certisign
3. Assinador da SERPRO
4. E em uma plataforma da Europa (https://ec.europa.eu/cefdigital/DSS/webapp-demo)

**Todos validam a assinatura como sendo correta.** Porém quando vou validar no:
https://verificador.iti.gov.br/verificador.xhtml
Ele informa que houve um erro ao gerar relatório, alguém já enfrentou esse problema?

**Comment by esaito** [comment]
As vezes acontece erro no processo do verificador do ITI, mas pode ser temporário como acesso à LCR por exemplo. 
Fiz um teste hoje com uma assinatura e não houve nenhum problema.

**Comment by esaito** [comment]
![relatorio_iti](https://user-images.githubusercontent.com/1101956/42107893-5302b382-7baf-11e8-96c9-72b04db11f4e.png)

**Comment by EngBruno** [comment]
Na verdade aconteceu uma coisa muito esquisita. Reiniciei o computador e criei um novo projeto, e tudo funcionou normalmente. Agora tudo não faz mais sentido. Obrigado pela atenção.
