### ISSUE TITLE
Suporte a Proxy Autenticado

### ISSUE THREAD

**Issue by wilsonleitejr** [demoiselle/signer#164]
Alguns ambientes de publicação possuem restrição à rota de saída para internet e a disponibilizam apenas através de um proxy autenticado.
O componente então poderia possibilitar de alguma forma o uso de proxy autenticado nas aberturas de conexões por ele realizadas. Ex.: baixa de repositório ICP-Brasil e LCR.

**Comment by joserenecampa** [comment]
A possibilidade já existe através de configurações da JVM. https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html. Acredito que não seja produtivo construir facilitadores dentro do Signer, que é focado em assinaturas digitais.

**Comment by wilsonleitejr** [comment]
De acordo, as configurações da JVM já supriria a necessidade do Proxy autenticado.
