### ISSUE TITLE
Javadocs publicados?

### ISSUE THREAD

**Issue by d3atiq** [demoiselle/signer#177]
Estou tentando entender a API para fazer uma assinatura CAdES attached com atributos do assinado (usando certificado de atributos), mas não encontro informação de como utilizar a API para isso.

Estou procurando os Javadocs da API mas não os encontro, nem na página do projeto (https://www.frameworkdemoiselle.gov.br/v3/signer/index.html), nem na página da respectiva documentação (https://www.frameworkdemoiselle.gov.br/v3/signer/docs/#).

Onde posso encontrar os Javadocs do Signer?

**Comment by esaito** [comment]
Ainda não estamos publicando o javadoc em formato HTML, mas se estiver utilizando uma IDE como Eclipse por exemplo essa documentação é apresentada. 

A parte da documentação sobre como gerar uma assinatura attached é essa: 
https://www.frameworkdemoiselle.gov.br/v3/signer/docs/policy-impl-cades-funcionalidades.html#policy-impl-cades-funcionalidades-assinar-attached
