### ISSUE TITLE
Co-assinaturas e contra-assinaturas (ICP Brasil)

### ISSUE THREAD

**Issue by joserenecampa** [demoiselle/signer#2]
Não esquecer de deixar retrocompatibilidade com a implementação atual.

**Comment by juliancesar** [comment]
Hoje a co assinatura já esta implementada pois é possivel gerar varias assinaturas para ummesmo documento.

**Comment by joserenecampa** [comment]
Faremos co-assinatura e contra-assinatura apenas do primeiro nível.
A especificação permite a criação de uma árvore complexa de assinaturas (co e contra).

**Comment by juliancesar** [comment]
Atividade migrada para controle interno.
