### ISSUE TITLE
Possível conflito de pacotes jar

### ISSUE THREAD

**Issue by auro-kray** [demoiselle/signer#207]
Ao gerar o pacote war, verifiquei que os jars gerados pelo signer, podem eventualmente conflitar com outros pacotes. Não sei se o maven trata esse problema automaticamente.

Por exemplo, o core do signer poderia eventualmente conflitar com o core do jasperreports.
No meu projeto em específico não tive nenhum problema pois as versões do core não coincidiram: core-3.3.3.jar do signer com o core-2.3.0.jar do jasperreports.

**Comment by esaito** [comment]
#130
