### ISSUE TITLE
ASSINADOR SERPRO 

### ISSUE THREAD

**Issue by fabiobbrandao** [demoiselle/signer#208]
Emerson, por favor, não conseguimos concluir a assinatura do dossiê eletrônico do Portal Único Siscomex. Uma hora dá a mensagem: "Nenhum drive foi encontrado." e em outro momento "quando desmarco as opções 
Arquivo LPA_CAdES.der não encontrado, executará download do arquivo.

**Comment by esaito** [comment]
O canal de contato para o Assinador SERPRO que parece ser o seu caso é: assinador.serpro@serpro.gov.br
