### ISSUE TITLE
CSP - erro ao efetuar a assinatura digital do conteúdo

### ISSUE THREAD

**Issue by ckilee** [demoiselle/signer#209]
Bom dia, ao efetuar a assinatura digital usando um provider via CSP ocasiona o seguinte erro na linha 708 do CAdESSigner.java:
17-05-2019 17:32:27 INFO  CAManager:236 - Procurando certificado no Provider: Provedor OFFLINE de cadeias ICP-Brasil  (icpbrasil.jks)
17-05-2019 17:32:27 INFO  CAManager:288 - Foram encontrados 4 níveis na cadeia do provider Provedor OFFLINE de cadeias ICP-Brasil  (icpbrasil.jks) 
17-05-2019 17:32:27 INFO  BasicCertificate:607 - Adicionando a url http://icp-brasil.certisign.com.br/repositorio/lcr/ACCertisignRFBG5/LatestCRL.crl
17-05-2019 17:32:27 INFO  BasicCertificate:607 - Adicionando a url http://icp-brasil.outralcr.com.br/repositorio/lcr/ACCertisignRFBG5/LatestCRL.crl
17-05-2019 17:32:27 INFO  OffLineCRLRepository:130 - O repositório de LCR (lista de certificados revogados)  foi criado com sucesso!.
17-05-2019 17:32:28 INFO  OffLineCRLRepository:101 - Foi encontrada uma LCR válida: http://icp-brasil.certisign.com.br/repositorio/lcr/ACCertisignRFBG5/LatestCRL.crl
17-05-2019 17:32:28 INFO  CAdESSigner:606 - OID do algoritmo que irá gerar assinatura: 1.2.840.113549.1.1.13
17-05-2019 17:32:28 INFO  CAdESSigner:607 - Nome do  algoritmo que irá gerar a assinatura : SHA512withRSA
17-05-2019 17:32:28 INFO  CAdESSigner:609 - Tamanho mínimo para chave:  2.048
17-05-2019 17:32:28 INFO  CAdESSigner:611 - Validando o tamanho da chave.
17-05-2019 17:32:28 INFO  CAdESSigner:623 - Efetuando a verificação dos atributos assinados
17-05-2019 17:32:28 INFO  CAdESSigner:655 - Ponto de Confiança ... CN=Autoridade Certificadora Raiz Brasileira v5, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
17-05-2019 17:32:28 INFO  CAdESSigner:655 - Ponto de Confiança ... CN=Autoridade Certificadora Raiz Brasileira v2, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
17-05-2019 17:32:28 INFO  CAdESSigner:667 - CN=Autoridade Certificadora Raiz Brasileira v5, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
17-05-2019 17:32:28 INFO  CAdESSigner:667 - CN=Autoridade Certificadora Raiz Brasileira v5, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR
17-05-2019 17:32:28 INFO  CAdESSigner:667 - CN=AC Certisign RFB G5, OU=Secretaria da Receita Federal do Brasil - RFB, O=ICP-Brasil, C=BR
17-05-2019 17:32:28 INFO  CAdESSigner:667 - CN=AC Secretaria da Receita Federal do Brasil v4, OU=Autoridade Certificadora Raiz Brasileira v5, O=ICP-Brasil, C=BR
17-05-2019 17:32:28 INFO  CAdESSigner:673 - O certificado pertence a cadeia CN=Autoridade Certificadora Raiz Brasileira v5, OU=Instituto Nacional de Tecnologia da Informacao - ITI, O=ICP-Brasil, C=BR que é permitida pela política  para gerar a assinatura.
17-05-2019 17:32:28 INFO  CAdESSigner:683 - Verificando o período de validade da politica
17-05-2019 17:32:28 WARN  PolicyValidator:55 - A Lista de politicas de assinatura do componente para o padrão usado está desatualizada, a data de atualização é: 15/02/2019 - 10:00:00
17-05-2019 17:32:28 INFO  PolicyValidator:56 - Buscando a LPA no arquivo local {0}.
17-05-2019 17:32:28 INFO  PolicyFactory:162 - Buscando a LPA no arquivo local C:\Users\carlos.lee\AppData\Local\Temp\lpas\LPA_CAdES.der.
17-05-2019 17:32:28 INFO  CAdESSigner:363 - Adicionando Certificado no CertStore
17-05-2019 17:32:28 INFO  CAdESSigner:691 - OID do algoritmo que irá gerar assinatura: 1.2.840.113549.1.1.13
17-05-2019 17:32:28 ERROR Assinador:64 - org.bouncycastle.operator.RuntimeOperatorException: exception obtaining signature: O conjunto de chaves não existe

	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder$1.getSignature(Unknown Source)
	at org.bouncycastle.cms.SignerInfoGenerator.generate(Unknown Source)
	at org.bouncycastle.cms.CMSSignedDataGenerator.generate(Unknown Source)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:708)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:510)
	at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doHashSign(CAdESSigner.java:868)
	at br.jus.trf4.assinador.signature.DemoiselleProviderImpl.assinarArquivo(DemoiselleProviderImpl.java:148)
	at br.jus.trf4.assinador.signature.DemoiselleProviderImpl.assinarArquivo(DemoiselleProviderImpl.java:114)
	at br.jus.trf4.assinador.gui.Assinador$AssinarAction$3.run(Assinador.java:529)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.security.SignatureException: O conjunto de chaves não existe

	at sun.security.mscapi.RSASignature.signHash(Native Method)
	at sun.security.mscapi.RSASignature.engineSign(RSASignature.java:386)
	at java.security.Signature$Delegate.engineSign(Unknown Source)
	at java.security.Signature.sign(Unknown Source)
	at org.bouncycastle.operator.jcajce.JcaContentSignerBuilder$SignatureOutputStream.getSignature(Unknown Source)
	... 10 more

**Comment by ckilee** [comment]
Já descobri o erro. No meu caso o algoritmo sha512withRSA dá pau, mas sha256withRSA dá certo.
Alguem poderia me explicar esse comentário que está no código?
CAdESSignerTest.java linha:331
> "devido a uma restrição do token branco, no windws só funciona com 256"

**Comment by esaito** [comment]
Esse é um problema com alguns drivers de Tokens Criptográficos no ambiente windows. Por algum motivo ele não funciona com algoritmo sha512. Não há uma explicação razoável, pois depende do token ou da leitora. 
Esses foram alguns dos diversos problemas que incentivaram o SERPRO a criar o NeoID que é uma nova modalidade de certificado digital: https://servicos.serpro.gov.br/neoid/

**Comment by ckilee** [comment]
Bom dia, obrigado pelo retorno.

Só para constar, tinha dado erro com SHA512, porém, não era erro do demoisele, era problema do provider e o mesmo foi corrigido. 

Acredito que casos de providers que dão erro com SHA512 podem ser que o provider que ainda não suporta SHA512
