### ISSUE TITLE
 Erro org.bouncycastle.asn1

### ISSUE THREAD

**Issue by chsguitar1** [demoiselle/signer#212]
Estou tentando assinar um arquivo em PKCS7 desta maneira
PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();
e estou obtendo este erro
 java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1InputStream.readObject()Lorg/bouncycastle/asn1/ASN1Primitive;

estou com dificuldades para implementar a assinatura com certificado A1

**Comment by esaito** [comment]
Que tipo de Assinatura está querendo implementar?

**Comment by chsguitar1** [comment]
Estou tentando implementar a assinatura Cades

Em sex, 28 de jun de 2019 às 14:48, Emerson Sachio Saito <
notifications@github.com> escreveu:

**Comment by esaito** [comment]
experimente rodar um destes testes:
https://github.com/demoiselle/signer/blob/master/policy-impl-cades/src/test/java/org/demoiselle/signer/policy/impl/cades/pkcs7/impl/CAdESSignerTest.java

**Comment by NicolasFelippe** [comment]
Boa noite, teve alguma solução
