### ISSUE TITLE
Informações de rede e instalação

### ISSUE THREAD

**Issue by fmartins-andre** [demoiselle/signer#242]
Olá. Seria possível informar os domínios, urls e IPs utilizados pelo app para conexão via internet? para que seja possível fazer as devidas liberações no firewall/proxy.

E seria de grande valia informações acerca do processo de instalação do app. Por exemplo, se existem parâmetros para a instalação do .exe para executar a instalação silenciosamente, para deploy pela rede com ferramentas tais como o PDQ Deploy.

**Comment by esaito** [comment]
Essa Issue está no projeto certo?
Não é uma aplicação, mas uma biblioteca java (.jar) por isso não existe .exe

**Comment by fmartins-andre** [comment]
@esaito supus que teriam informações acerca desses temas aqui, visto que o assinador do serpro utiliza o framework. Talvez teria sido melhor abrir a issue no repo da framework, mas aparentemente não terei essa resposta por lá também.
de toda forma obrigado.

**Comment by esaito** [comment]
para o Assinador SERPRO, mande e-mail para: assinador.serpro@serpro.gov.br
