### ISSUE TITLE
Listar certificados disponíveis do usuario via web application.

### ISSUE THREAD

**Issue by Victor5200** [demoiselle/signer#243]
Olá pessoal, atualmente estou rodando um projeto que utiliza o framework demoiselle e JEE 8 aonde localmente eu consigo listar os certificados instalados na maquina do usuario com o código abaixo: 

`
KeyStoreLoader keyStoreLoader = KeyStoreLoaderFactory.factoryKeyStoreLoader(); KeyStore return keyStoreLoader.getKeyStore()
`

Porem ao subir a aplicação em um servidor web ( não local ) o mesmo código acima não consegue reconhecer os certificados do usuario. 

Alguém sabe uma forma de pegar essa lista de certificados ( no Client Side ) utilizando a aplicação web ( Server Side ) ?

**Comment by esaito** [comment]
Não é possível listar os certificados do cliente, nem utilizá-los para fazer Assinaturas por exemplo, através de uma aplicação web. Se for fazer apenas o login na aplicação é possível configurar o servidor de aplicações para fazer a autenticação.
