### ISSUE TITLE
Integração com aplicação WEB

### ISSUE THREAD

**Issue by wictrix** [demoiselle/signer#246]
Pessoal, sou desenvolvedor de um sistema  GED que roda em WEB. Preciso implementar a assinatura digital de documentos. Voces tem exemplo de como integrar o Signer Desktop com a web browser?

**Comment by esaito** [comment]
Na versão anterior (Demoiselle Certificate) a integração era via JAVA-WS (JNLP) na versão atual não há solução integrada no Java pois o mesmo abandonou o WS depois da versão 9. O SERPRO desenvolveu o  [(Assinador SERPRO)](https://www.serpro.gov.br/links-fixos-superiores/assinador-digital/assinador-serpro) que provê essa funcionalidade. Porém o suporte é fornecido apenas para órgãos públicos que façam contrato com o SERPRO. Para mais informações envie e-mail para assinador.serpro@serpro.gov.br

**Comment by wictrix** [comment]
Emerson, obrigado pelo retorno.
Neste caso a versão atual só pode ser utilizada por órgãos públicos, voce conhece outra API para indicar, que pode ser utilizada por empresas privadas?

**Comment by esaito** [comment]
O Assinador SERPRO ([https://www.serpro.gov.br/assinador-digital/](https://www.serpro.gov.br/assinador-digital/)) é gratuíto e pode ser utilizado por qualquer pessoa física ou jurídica que possua um certificado ICP-Brasil. O suporte que me refiro é que para integrar com um aplicação é preciso algumas alterações na aplicação. No caso de órgão públicos o SERPRO oferece suporte e treinamento para essas atividades.
