### ISSUE TITLE
não permite parametrizar o algoritmo para hash.

### ISSUE THREAD

**Issue by esaito** [demoiselle/signer#25]
atualmente não está surtindo efeito setar como parâmetro a algorítimo de hash. ex: signer.setAlgorithm(SignerAlgorithmEnum.SHA512withRSA);

**Comment by juliancesar** [comment]
@esaito, acredito que esta demanda esteja concluída, podemos fechar?

**Comment by juliancesar** [comment]
@joserenecampa, você poderia revisar essa questão para nós?

**Comment by esaito** [comment]
Está concluída. pode ser revisada e fechada.

**Comment by juliancesar** [comment]
Eu testei e parece que esta tudo correto.
