### ISSUE TITLE
Implementação de assinatura XAdES

### ISSUE THREAD

**Issue by FabianoK** [demoiselle/signer#250]
Implementação de assinatura em documentos XML no parão XAdES

**Comment by jhonattanS** [comment]
Olá pessoal, sou colaborador numa empresa do ramo educacional, e estamos com essa demanda de assinatura. Alguma previsão para essa funcionalidade? Tenho estudado o xades4j, até consegui assinar um xml com a biblioteca, mas como me falta um conhecimento mais profundo das normas do ICP-Brasil, , não está claro se os padrões implementados pela biblioteca se encaixam na nossa realidade. Agradeço se a alguém puder dar uma luz nessa questão e sobre o desenvolvimento dessa funcionalidade.

**Comment by FabianoK** [comment]
Bom dia.

A versão atual do Demoiselle Signer conta com funcionalidades de assinatura
no padrão XAdES.  Ainda não está completamente pronta mas você pode
experimentar seguindo o fragmento de código abaixo.

        XMLSigner xades = new XMLSigner();
xades.setAlias("ALIAS");        xades.setKeyStore("KEYSTORE);
xades.setPasswd("SENHA DO KEYSTORE");

        String fileName = "NOME DO ARQUIVO XML";

        //Caso deseje alterar a política, caso seja definida como null
será utilizada a política AD_RB_CADES_2_3"
xades.setPolicyId(null);
xades.setSignaturePackaging(SignaturePack.ENVELOPED);
Document doc = null;        Document sourceDoc = null;
       doc = xades.sign(fileName);


Em ter., 22 de dez. de 2020 às 12:45, jhonattanS <notifications@github.com>
escreveu:

**Comment by jhonattanS** [comment]
@FabianoK Obrigado pelo retorno!

Tentei simular o código que você repassou utilizando a versão 3.6.3 do maven, mas parece não estar implementado o XMLSigner. Sabe me dizer se está numa versão especifica?

**Comment by FabianoK** [comment]
Tem razão, o pacote XAdES ainda não está sendo distribuído com o as versões
do Signer. O consórcio Europeu tem uma solução que pode ajudar você a
desenvolver sua
aplicação
https://ec.europa.eu/cefdigital/DSS/webapp-demo/doc/dss-documentation.html.
Na sessão "XAdES with implicit policy" tem um exemplo de como utilizar
políticas
de assinatura, coloque o oid 2.16.76.1.5.1.2.1 no setId para ficar no
padrão brasileiro.

Esta documentação foi a principal referência para o desenvolvimento do
componente XAdES do Demoiselle Signer.

**Comment by jhonattanS** [comment]
@FabianoK Muito obrigado!
