### ISSUE TITLE
Nao foi possivel resgatar as CAs do provedor AC DIGITALSIGN RFB G2

### ISSUE THREAD

**Issue by thigorqueiroz** [demoiselle/signer#258]
Olá, estou com  a seguinte dificuldade:

Problema no momento de assinar ultilizando um certificado com a AC Intermediaria AC DIGITALSIGN RFB G2.
O  projeto já está em produção há um bom tempo e nele foi empacotado o módulo **chain-icp-brasil**. 
Foi verificado se a AC estaria devidamente distribuída nos _arquivos http\://repositorio.serpro.gov.br/icp-brasil/ACcompactado.zip_ e _http\://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/ACcompactado.zip_.

Exception:
org.demoiselle.signer.policy.impl.cades.SignerException: org.demoiselle.signer.policy.impl.cades.SignerException: Nao foi possivel resgatar as CAs do provedor CN=AC DIGITALSIGN RFB G2, OU=Secretaria da Receita Federal do Brasil - RFB, O=ICP-Brasil, C=BR

**Existe algo que pode ser verificado além do que já foi?**

**Comment by esaito** [comment]
Isso só ocorreria se o equipamento que está executando não tem acesso aos endereços [http://repositorio.serpro.gov.br/icp-brasil/ACcompactado.zip](http://repositorio.serpro.gov.br/icp-brasil/ACcompactado.zip) ou [http://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/ACcompactado.zip](http://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/ACcompactado.zip). Qual a versão do componente está usando?

**Comment by thigorqueiroz** [comment]
O problema estava em um bloqueio na rede, como você mesmo disse. Obrigado Emerson!
