### ISSUE TITLE
Possibilitar assinar PKCS#7 atachada sem definir PolicyFactory.Policies 

### ISSUE THREAD

**Issue by alvaromateus** [demoiselle/signer#279]
Foi verificado que determinados sistemas realizam verificação somente da cadeia de certificados e retornam erro caso seja inserida na assinatura informações da LPA (Lista de Políticas de Assinatura). Um exemplo deste sistema é o sistema de Processos Judiciais digital do PR (Projudi). 

Entendo que tal verificação não atenderá a DOC-ICP-15, porém conforme verificação em https://verificador.iti.gov.br/verifier-2.6/ este tipo de assinatura sem LPA atende a MP 2.200-2/2001.

![02](https://user-images.githubusercontent.com/7135/101378928-71c44180-3892-11eb-8316-015cef824407.png)
![01](https://user-images.githubusercontent.com/7135/101378932-725cd800-3892-11eb-9466-2aec15b74061.png)

**Comment by esaito** [comment]
O Projudi deveria fazer exatamente o contrário, é quase um absurdo um sistema acusar erro em um atributo obrigatório para ICP-Brasil, que é a política. 
Quando o relatório diz que atende MP 2.200-2/2001,significa apenas que foi usado um certificado da Cadeia ICP-Brasil e o nem o arquivo nem a assinatura foram corrompidos. Tem validade legal, mas não irá garantir temporalidade ou tempestividade da assinatura, por exemplo.
