### ISSUE TITLE
Certificação PA AD RB - versão 2.2

### ISSUE THREAD

**Issue by spinalsc** [demoiselle/signer#281]
Bom dia!

Estamos utilizando a certificação PAdES, com um certificado digital de PF para fins de testes.
Na classe SigningCertificateV2 , no método getValue() temos a utilização de dois objetos do tipo certificado. Um deles, na posição 0 do vetor temos instanciado nosso certificado, porém há a necessidade de utilizar neste método um outro objeto do tipo certitficado, na posição 1.

X509Certificate cert = (X509Certificate) certificates[0];
X509Certificate issuerCert = (X509Certificate) certificates[1];

Não encontrei na documentação referencia a este segundo, por assim dizer, objeto.

**Comment by esaito** [comment]
Não ficou clara sua pergunta, está com algum problema na assinatura ou validação?
