### ISSUE TITLE
Adicionando uma assinatura digital a partir de um certificado armazenado localmente - erro no algoritmo

### ISSUE THREAD

**Issue by guitarpe** [demoiselle/signer#282]
Bom dia.

Estou tentando adicionar uma assinatura digital num pdf a partir de um certificado armazenado localmente. No log ocorre tudo normalmente ele verifica o certificado, encontra a LCR válida porém não prossegue e  mostra o seguinte warning:

.m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.operator.DefaultSignatureAlgorithmIdentifierFinder]

o meu código é o seguinte:

//pega a senha criptografada
Criptografar cripto = new Criptografar();
String senhacertificado = cripto.resgatarSenha(properties.getProperty("certificado.dados.senha"));
String caminhoacertificado = properties.getProperty("certificado.dados.arquivopfx");    
String keystore_password = senhacertificado; 

//pega o keystore a partir do certificado e senha
KeyStore keystore = KeyStore.getInstance("PKCS12");
keystore.load(new FileInputStream(caminhoacertificado), keystore_password.toCharArray());
String alias = keystore.aliases().nextElement();    
PrivateKey privateKey = (PrivateKey) keystore.getKey(alias, keystore_password.toCharArray());

//pega o certificado
Certificate[] certificates = keystore.getCertificateChain(alias);   
	    
//verifica as políticas e o algoritmo usado
Policies policy = Policies.AD_RA_PADES_1_2;
SignerAlgorithmEnum algorithm = SignerAlgorithmEnum.SHA256withRSA;

//inicia a assinatura do documento
PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();

//seta os parâmetros de assinatura no documento
signer.setCertificates(certificates);
signer.setPrivateKey(privateKey);
signer.setSignaturePolicy(policy);
signer.setAlgorithm(algorithm);
//signer.addAttribute(new MessageDigest(hash));

//pega o documento original
File fileIn = new File(origem);
byte[] content = Files.readAllBytes(fileIn.toPath());
byte[] signature = signer.doDetachedSign(content);

//define o arquivo de saída
File file = new File(destino+".p7s");
BufferedOutputStream bos = new BufferedOutputStream(new FileOutputStream(file));

//escreve a assinatura
bos.write(signature);
bos.close();

**Comment by esaito** [comment]
Para gerar um .p7s vc deve usar uma política CAdES, no seu código está usando PAdES e ainda é uma que não está implementada.

Verifique esse exemplo:

[https://github.com/demoiselle/signer/blob/master/policy-impl-cades/src/test/java/org/demoiselle/signer/policy/impl/cades/pkcs7/impl/CAdESSignerTest.java](https://github.com/demoiselle/signer/blob/master/policy-impl-cades/src/test/java/org/demoiselle/signer/policy/impl/cades/pkcs7/impl/CAdESSignerTest.java)

**Comment by guitarpe** [comment]
Consegui gerar o .p7s mas somente usando o AD_RB_CADES_2_3, quando tentava usar AD_RT_CADES_2_3 com o carimbo do tempo mostrava um erro "O token de carimbo de tempo foi rejeitado". Eu gostaria de criar um arquivo PDF assinado, como posso fazer isso usando este p7s gerado de forma que este pdf se torna legalmente válido?

**Comment by esaito** [comment]
Para usar carimbo do tempo precisa de contrato com a Autoridade de Carimbo do Tempo do SERPRO. Se as assinaturas forem geradas apenas pelo sistema pode utilizar apenas o componente Signer veja esses exemplos: [https://github.com/demoiselle/signer/tree/master/policy-impl-pades/src/test/java/org/demoiselle/signer/policy/impl/pades/pkcs7/impl](https://github.com/demoiselle/signer/tree/master/policy-impl-pades/src/test/java/org/demoiselle/signer/policy/impl/pades/pkcs7/impl)
Mas se a Assinatura for feita no lado cliente (usuário com token, ou smartcard) veja o Assinador SERPRO:
[https://serpro.gov.br/links-fixos-superiores/assinador-digital/assinador-serpro](https://serpro.gov.br/links-fixos-superiores/assinador-digital/assinador-serpro)
