### ISSUE TITLE
Refatorar o código do Signer para permitir uma integração com o Assijus

### ISSUE THREAD

**Issue by crivano** [demoiselle/signer#293]
O assinador da Justiça Federal, [Assijus](https://github.com/assijus/assijus), utiliza o conceito de um assinador leve, no qual a montagem do envelope é feita no servidor, cabendo ao assinador apenas produzir a assinatura utilizando RSA e SHA256.

Para viabilizar a integração do Assijus com o Deimoselle, será necessário refatorar o código do Signer criando um método que produz os atributos assináveis, Signed Attributes, e outro que empacota o envelope.

```java
/**
 * Recebe o certificado, o hash do documento, que pode ser sha256 para as
 * políticas atuais, o identificador da política a ser utilizada e a data e hora
 * da assinatura. Produz um array de bytes contendo a tabela de atributos
 * assinados.
 */
byte[] produceSignedAttributes(X509Certificate certificate, byte[] hash, Policies policy, Date dateTime) {

}

/**
 * Recebe o certificado, o hash do documento, o identificador da política a ser
 * utilizada, a data e hora da assinatura e um array de bytes contento a
 * assinatura em si. Produz um array de bytes contendo o envelope CMS/PKCS7 da
 * assinatura.
 */
byte[] produceEnvelope(X509Certificate certificate, byte[] hash, Policies policy, Date dateTime, byte[] signature) {

}
```

Observe que o parâmetro dateTime está presente nos dois métodos porque o método produceEnvelope() precisa, também, reproduzir os atributos assináveis pois eles são parte do envelope PKCS7. Na chamada ao método produceEnvelope(), não estamos passando como parâmetro os atributos assináveis, então eles precisarão ser "recriados" exatamente iguais aos que foram usados para produzir a "signature". Portanto, a data precisa também ser exatamente a mesma.

**Comment by esaito** [comment]
https://github.com/demoiselle/signer/issues/139

**Comment by crivano** [comment]
Não entendi muito bem a proposta da #139, mas se no final tivermos os métodos acima, está ótimo.
