### ISSUE TITLE
Assinatura de PDF em CaDEs, assinatura de arquivo XML em CaDEs. Assinador Arisp x Assinador Serpro

### ISSUE THREAD

**Issue by emiliostzsp** [demoiselle/signer#299]
Boa tarde! Estou gerando a assinatura de documentos PDF em CADES pelo Demoiselle. Ele gera o documento ps7 normalmente. Ele é validado pelo site de conformidade do ITI. Porem eu não consigo visualizar o ps7 no AdobeReader. Já documentos assinados da mesma forma pelo Assinador da Arisp abrem normalmente o arquivo p7s no AdobeReader. Arquivos XML que eram assinados anteriormente pelo Assinador Arisp abriam normalmente. Agora assinados pelo Demoiselle Signer não abrem mais. É como se os arquivos estivessem corrompidos. Quando assino os arquivos em CADES pelo assinador do Serpro acontece a mesma coisa que acontece quando assino no Demoiselle Signer. Tem algo que posso fazer para corrigir isso?

[ASSINADOR_DEMOISELLE_FRAMEWORK_TESTE ASSINATURA DE PDF-CADES.PDF.zip](https://github.com/demoiselle/signer/files/6672543/ASSINADOR_DEMOISELLE_FRAMEWORK_TESTE.ASSINATURA.DE.PDF-CADES.PDF.zip)
[AssinadorARISP.zip](https://github.com/demoiselle/signer/files/6672548/AssinadorARISP.zip)

**Comment by israelaece** [comment]
Eu não conheço muito bem o Demoiselle, mas tive um problema semelhante recentemente, porém eu utilizo C# com BouncyCastle (que também é utilizado pelo Demoiselle). No meu caso, a solução foi, ao gerar o pacote CMS (`CmsSignedDataGenerator`) informar a codificação como `DER`:

`
gen.Generate(new CmsProcessableByteArray(original), true).GetEncoded("DER");
`

Talvez o @esaito ajude a identificar onde pode customizar esta geração/codificação.

**Comment by emiliostzsp** [comment]
Boa tarde @israelaece. Obrigado pelo comentário. É que sou novo em programação Java. Até agora foi bem o desenvolvimento. Só me deparei com esse problema.  Agradeço pelo seu comentário. Vou entrar em contato com o @esailto.

**Comment by emiliostzsp** [comment]
Dois arquivos .p7s assinados em CADES. Um pelo DemoiselleSigner, o outro pelo assinador Arisp. Pode abrir os dois num editor de texto simples. Vocês verão que o que foi assinado pelo demoiselle signer apresenta inconsistência no conteúdo do arquivo XML. O assinado pelo Assinador da Arisp mantem intacto a estrutura do arquivo XML. Como resolver isso?
[_DEMOISELLESIGNER_CDR031606.211.XML.zip](https://github.com/demoiselle/signer/files/6683017/_DEMOISELLESIGNER_CDR031606.211.XML.zip)

**Comment by emiliostzsp** [comment]
Resolvido. 
				if (encapsulate)
				{
					//octs = new BEROctetString(bOut.toByteArray()); Alterei aqui Sílvio
					octs = new DEROctetString(bOut.toByteArray());
				}

**Comment by tiagocelso** [comment]
@emiliostzsp Na versão atual estou com o mesmo problema. Você lembra onde exatamente você aplicou a alteração? Acho que faz um pouco de tempo né? rs

**Comment by tiagocelso** [comment]
@esaito Poderia me ajudar com esse caso?
