### ISSUE TITLE
ConfigurationRepo não seta usuario e senha do Proxy

### ISSUE THREAD

**Issue by fbtlopes** [demoiselle/signer#305]
A classe ConfigurationRepo no método "public void setProxy(String hostName, String port, final String userName, final String password)" não seta a autenticação do proxy quando o usuário e senha dos mesmos estão preenchidos

**Comment by esaito** [comment]
Tem alguma log de execução e/ou do proxy? 
Esse método é bastante usado.

**Comment by fbtlopes** [comment]
A log que tenho aqui é somente essa: "Não foi possivel conectar a: http://repositorio.serpro.gov.br/lcr/acserproacfv5.crl .Server returned HTTP response code: 407 for URL: http://repositorio.serpro.gov.br/lcr/acserproacfv5.crl"

Contornei usando o public void setProxy(Proxy proxy).

Na assinatura que comentei na issue parece que o if da linha 396 está errado. Ele está setando a autenticação quando o userName NÃO está preenchido
