### ISSUE TITLE
Timestamp válido não reconhecido pelo Adobe Reader

### ISSUE THREAD

**Issue by salguei-ro** [demoiselle/signer#314]
Oi, pessoal.

Estou recebendo um carimbo de tempo válido e integrando no código. Porém, quando assino o PDF, o Adobe Reader/Acrobat reporta que "o horário de assinatura é o que consta no computador do signatário".

Os PDFs assinados (certificado + timestamp) pelo Signer tem validação de carimbo de tempo "correta" quando aberto no Adobe, ou é assim mesmo - i.e., sempre vai aparecer essa mensagem?

**Comment by esaito** [comment]
Tanto a Assinatura como o carimbo do tempo serão reconhecidos pelo Adobe.
Está usando qual política para Assinar?
Qual ACT?
