### ISSUE TITLE
Selo ou carimbo da assinatura no documento

### ISSUE THREAD

**Issue by wesleyagomes** [demoiselle/signer#348]
Boa tarde pessoal, em primeiro lugar gostaria de parabenizar muito pela API, funciona muito bem, Obrigado mesmo por disponibilizar.
Tenho uma dúvida. Na verdade não encontrei na documentação, é uma coisa simples mas que me faz muita falta.
Geralmente as assinaturas digitais acompanham algum selo ou carimbo estampado no documento PDF, onde ao clicar sobre esse selo ou carimbo o mesmo nos leva ao painel com os dados da assinatura (usando o adobe reader por exemplo).
Gostaria de saber se existe alguma forma de implementar esse selo, seja com uma imagem ou um campo texto mesmo para enriquecer o documento assinado, sim sim gostaria da indicação do trecho de código fonte que faz tal tarefa.
PS.: anexei um exemplo de selo que o assinador da serpro produz.
Não sei se este é o lugar apropriado para postar essa dúvida, mas agradeço pela atenção dispensada.

![exemplo](https://user-images.githubusercontent.com/110124913/181342032-ab13d4a2-0340-4746-8fd9-204b9cc47f2f.png)

**Comment by esaito** [comment]
Esse é um recurso que não é feito pelo componente do Demoiselle, você pode usar uma biblioteca para manipular o PDF e incluir uma assinatura do tipo visiível. Veja: [https://pdfbox.apache.org/](https://pdfbox.apache.org/)

**Comment by wesleyagomes** [comment]
Show de bola. Futuramente será implementado no Demoiselle ou está fora dos
planos?
Muito obrigado pelo retorno.

Em ter, 2 de ago de 2022 21:27, Emerson Sachio Saito <
***@***.***> escreveu:
