### ISSUE TITLE
IdSigningTime | Reprovado. Atributo assinado proibido presente: 1.2.840.113549.1.9.5

### ISSUE THREAD

**Issue by CesarPinheiro** [demoiselle/signer#354]
Quando gerei arquivo PDF assinado para ser verificado, recebo a seguintes mensagens de erro/alerta:

***************
IdSigningTime | Reprovado. Atributo assinado proibido presente: 1.2.840.113549.1.9.5
Data da assinatura | December 31, 1969 at 9:00:00 PM BRT
Mensagem de alerta | SignDate no dicionário da assinatura encontra-se em um período antes da validade do certificado do assinante.
***************

Estou usando a bibliotec Demoiselle.
A rotina de assinatura não foi alterada e funcionava sem problemas
.
                        PDSignature f_signature = new PDSignature();
                        f_signature.setFilter(PDSignature.FILTER_ADOBE_PPKLITE);
                        f_signature.setSubFilter(PDSignature.SUBFILTER_ADBE_PKCS7_DETACHED);
                        f_signature.setName("");
                        f_signature.setLocation("");
                        f_signature.setReason("");
                        f_signature.setContactInfo("");
                        Calendar f_dataTeste = Calendar.getInstance(TimeZone.getTimeZone("America/Sao_Paulo"));
                        f_signature.setSignDate(f_dataTeste);

Quando vou depurar, vejo a seguinte mensagem do Demoiselle:

***************
AssinadorPdf.AssinadorPdf: data:         java.util.GregorianCalendar[time=1660147238959,areFieldsSet=true,areAllFieldsSet=true,lenient=true,zone=sun.util.calendar.ZoneInfo[id="America/Sao_Paulo",offset=-10800000,dstSavings=0,useDaylight=false,transitions=93,lastRule=null],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2022,MONTH=7,WEEK_OF_YEAR=33,WEEK_OF_MONTH=2,DAY_OF_MONTH=10,DAY_OF_YEAR=222,DAY_OF_WEEK=4,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=1,HOUR_OF_DAY=13,MINUTE=0,SECOND=38,MILLISECOND=959,ZONE_OFFSET=-10800000,DST_OFFSET=0]
***************

Estou usando a última versão do Demoseille via Maven: 4.1.0

Estou usando https://verificador.iti.gov.br/ para verificar.

**Comment by CesarPinheiro** [comment]
I Am using https://verificador.iti.gov.br/ to verify.

**Comment by CesarPinheiro** [comment]
Fechada por falta de resposta.

**Comment by esaito** [comment]
https://www1.folha.uol.com.br/mercado/2022/08/serpro-contratado-para-monitorar-internet-nas-eleicoes-entra-em-greve.shtml
