### ISSUE TITLE
Extrair a chave privada de um certificado informado pelo cliente 

### ISSUE THREAD

**Issue by nishida98** [demoiselle/signer#355]
Sou dev de uma consultoria e estamos desenvolvendo uma aplicação web para assinatura de documentos com certificados digitais A3. Gostaria de saber se há alguma forma de fazer o load desse certificado para o KeyStore e assim manipular a chave privada. 

Desde já, obrigado pela ajuda!

**Comment by esaito** [comment]
Não é possivel manipular a chave privada do certificado A3 sem que haja algum programa instalado no lado do usuário.
O SERPRO provê uma solução, veja essa documentação: [https://www.assinadorserpro.estaleiro.serpro.gov.br/minimalista/tutorial/](https://www.assinadorserpro.estaleiro.serpro.gov.br/minimalista/tutorial/)

**Comment by nishida98** [comment]
Me desculpe pela demora em responder. 
Entendi, devido a essa restrição optamos por seguir outro caminho. 
Obrigado pela ajuda.
