### ISSUE TITLE
Problema na documentação de core

### ISSUE THREAD

**Issue by claudio-fuzitaki** [demoiselle/signer#356]
Estava atualizando o pom para usar a versão 4.0.0

Em https://www.frameworkdemoiselle.gov.br/v3/signer/docs/core-configuracao.html, a configuração apresentada

        		<dependency>
				<groupId>org.demoiselle.signer</groupId>
				<artifactId>core</artifactId>
				<version>4.0.0</version>
			</dependency>

e relacionadas não funcionam.

No link de https://repo1.maven.org/maven2/org/demoiselle/signer/core/ não tem versão 4.0.0, subi na hierarquia e vi que criaram um /signer-core para as versões mais novas. O Maven pelo menos encontra 

<artifactId>signer-core</artifactId>
<version>4.0.0</version>

mas ainda não consegui rodar o projeto.

**Comment by claudio-fuzitaki** [comment]
Lendo a documentação inacabada no GitHub vi que Configuration mudou para ConfigurationRepo, e era outra razão para não conseguir rodar. Por favor ajustem a documentação da versão 4.0.0.

**Comment by esaito** [comment]
Agradecemos pela informação, e como um projeto de software livre, ele está aberto à contribuições, caso tenha esse interesse o modulo é esse: https://github.com/demoiselle/signer/tree/master/documentation

**Comment by esaito** [comment]
#367
