### ISSUE TITLE
Não foi possível resgatar as CAs do certificado no provedor

### ISSUE THREAD

**Issue by lincolnbf1** [demoiselle/signer#378]
Na versão 4.0.0 
```

class br.com.exception.SignerException - Nao foi possível resgatar as CAs do certificado no provedor CN=SERASA Certificadora Digital v5, O=ICP-Brasil, C=BR - 113
org.demoiselle.signer.policy.impl.cades.SignerException: Nao foi possível resgatar as CAs do certificado no provedor CN=SERASA Certificadora Digital v5, O=ICP-Brasil, C=BR
    at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:297)
    at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doSign(CAdESSigner.java:254)
    at org.demoiselle.signer.policy.impl.cades.pkcs7.impl.CAdESSigner.doHashSign(CAdESSigner.java:692)
```
....

Estava funcionando 100% até um tempo atrás. Sabem me dizer se a atualização pra versão 4.2.0 resolveria esse problema ou não tem nada haver

**Comment by esaito** [comment]
Não era para fazer diferença, mas é sempre bom estar na última versão.
Está com a dependência para: chain-icp-brasil ?
Não aparece mais nada nos logs?

**Comment by lincolnbf1** [comment]
Cara, o motivo era muito bizarro. Estava rodando essa assinatura em uma thread, tirando da thread simplesmente voltou a funcionar. Não faço idéia do por que, mas resolvi assim.
