### ISSUE TITLE
Erro ao validar assinatura com certificado da cadeia do SERPRO RFB v4

### ISSUE THREAD

**Issue by tobiaspetry** [demoiselle/signer#384]
A partir da versão major 4, a validação de assinatura de documentos com certificados cujo issuer seja o Autoridade Certificadora SERPRORFBv4 está lançando erro:

> Não foi possível resgatar as CAs do certificado no provedor CN=Autoridade Certificadora SERPRORFBv4, OU=Secretaria da Receita Federal do Brasil - RFB, O=ICP-Brasil, C=BR

Identificamos que na major 4 o certificado SERPRO RFB v4, expirado em outubro de 2021, foi removido da keystore icpbrasil.jks, assim como outros certificados que venceram.

Entendo que um certificado vencido ou com vencimento em algum certificado da cadeia não pode ser usado para uma nova assinatura. Porém, para validação de um documento assinado no passado, durante a vigência de toda a cadeia, os antigos CA deveriam ainda ser considerados.

**Comment by esaito** [comment]
Tem razão. Poderia anexar o arquivo e assinatura para que possamos usar para testes?

O ITI disponibiliza 2 arquivos, no caso deveríamos nos basear no cadeia completa.

[Cadeia Vigente](https://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/ACcompactado.zip)
	
 [Cadeia Completa](https://acraiz.icpbrasil.gov.br/credenciadas/CertificadosAC-ICP-Brasil/ACcompactadox.zip)

**Comment by tobiaspetry** [comment]
De fato, alterando o caminho do ITI para a cadeia completa (ACCompactadox.zip e hashsha512x.txt) a validação funciona. Conseguimos validar alterando os caminhos no arquivo chain-icp-brasil-config-default.properties. Obrigado!
