### ISSUE TITLE
conteudo do PDF assinado fica corrompido

### ISSUE THREAD

**Issue by jradesenv** [demoiselle/signer#390]
Pessoal, estou tentando utilizar a lib da seguinte forma na esperança de assinar meu PDF e mante-lo legivel, mas o arquivo pós assinatura apesar de passar com sucesso na validacao do ITI, ao abrir ele vejo que o conteudo ficou todo errado, cheio de espaços em branco e perdeu boa parte do conteudo original.  
Estou correto em esperar que esse metodo doAttachedSign retorne o pdf assinado ainda legivel ou é esperado que ele fique inutil aos olhos do usuário e apenas valido para validacao do ITI?

```
implementation group: 'org.demoiselle.signer', name: 'policy-impl-cades', version: '3.7.1'.  

implementation group: 'org.demoiselle.signer', name: 'chain-icp-brasil', version: '3.7.1'

```

```

byte[] content = Base64.getDecoder().decode(input.getBase64());
// Salvar o PDF assinado em um arquivo
String caminhoArquivo1 = "cert/nao_assinado.pdf";
salvarPDFAssinado(content, caminhoArquivo1);

PKCS7Signer signer = PKCS7Factory.getInstance().factoryDefault();
aplicarCertificado(signer);

byte[] assinado = signer.doAttachedSign(content);

// Salvar o PDF assinado em um arquivo
String caminhoArquivo = "cert/assinado.pdf";
salvarPDFAssinado(assinado, caminhoArquivo);

```
  
  
  Nesse teste do print abaixo mesmo o pdf resultante ficou completamente em branco:
  
<img width="1056" alt="image" src="https://github.com/demoiselle/signer/assets/5112752/4f8615b4-06f9-4aea-b0e4-10b94b90761d">

E ainda assim valido no ITI:
<img width="1056" alt="image" src="https://github.com/demoiselle/signer/assets/5112752/a58b2931-981a-4472-97cf-25ca4e7b75b1">

**Comment by esaito** [comment]
Olá

O método que está usando faz a assinatura do tipo Attached  ([https://docs.oracle.com/cd/E19398-01/820-1228/gfnmj/index.html](https://docs.oracle.com/cd/E19398-01/820-1228/gfnmj/index.html)), serve para qualquer tipo de arquivo. 
Portanto esse método não gera um PDF assinado.
Para fazer isso você precisa manipular o PDF usando uma lib como o PDFBox por exemplo ( https://github.com/demoiselle/signer/blob/master/policy-impl-pades/src/test/java/org/demoiselle/signer/policy/impl/pades/pkcs7/impl/PDFSignerTest.java)
Ou poderia utilizar a integração com o Assinador SERPRO: [https://www.assinadorserpro.estaleiro.serpro.gov.br/minimalista/tutorial/](https://www.assinadorserpro.estaleiro.serpro.gov.br/minimalista/tutorial/)

**Comment by esaito** [comment]
Exato, a assinatura gerada por aquele método embute o PDF dentro dela. 
Como está resolvido vou fechar a Issue.
