### ISSUE TITLE
Problema na visualização dos certificados

### ISSUE THREAD

**Issue by rsmont** [demoiselle/signer#391]
Prezados,
Estamos tendo um problema ao chamarmos o Assinador quando aparecem os certificados para ser escolhido aquele que iremos usar. O botão Selecionar aparece em dois pontos (print) e não conseguimos fazer a escolha. Já ocorreu algo com vocês nesse sentido?
![Capturar](https://github.com/demoiselle/signer/assets/1914968/9b8d6312-aa3b-424a-bf3d-fbf5a4d45874)

**Comment by esaito** [comment]
O suporte para o Assinador SERPRO é através deste e-mail: assinador.serpro@serpro.gov.br

**Comment by rsmont** [comment]
Grato!
