### ISSUE TITLE
Problema ao resgatar as CA's

### ISSUE THREAD

**Issue by Victor-Marquez** [demoiselle/signer#403]
Boa tarde. Tudo bem?

Estou com problema ao gerar a assinatura eletrônica no padrão CAdES.

Print do Erro
![erro](https://github.com/demoiselle/signer/assets/42700454/077740df-8a93-4429-8035-db107d2728bb)

Print do fonte
![image](https://github.com/demoiselle/signer/assets/42700454/5f3a5d3b-3f4d-4492-8fff-9564c86413a2)

** Variável pathArquivo, seria o meu arquivo .txt que irei utilizar para assinar.
** Estou gerando um arquivo destacado (detached) 

Estava debugando, e na classe CAManager.class, no método getCertificateChain, quando vai realizar a busca da Collection do tipo ProviderCA, está vindo vazia
![image](https://github.com/demoiselle/signer/assets/42700454/2f0648e2-7b90-4ae4-b2fc-275f06dd05c2)

Alguma ideia do que poderia ser?

**Comment by esaito** [comment]
Está incluindo a dependência para o componente chain-icp-brasil?

**Comment by Victor-Marquez** [comment]
Sim. Estou utilizando.
![image](https://github.com/demoiselle/signer/assets/42700454/729f45ce-d9aa-41f7-bcdb-288893328320)

**Comment by Victor-Marquez** [comment]
Boa tarde Emerson. Tudo bem?

Descobri o problema. Conforme a imagem anterior, onde mostro a importação das dependências, o artifactId chain-icp-brasil, estava no scope de test, por esse motivo não estava funcionando.

Acabei fazendo o import do maven repository e nele consta o escopo de teste.
![image](https://github.com/demoiselle/signer/assets/42700454/d91d6775-ad74-4022-9e8d-8743a1448944)

Tinha feito o download do projeto (branch master) e utilizado a classe CAdESSignerTest.java para testar, porém, estava fazendo uma cópia dessa classe e criando uma classe main para poder executá-la. 
Porém, no pom.xml a dependência também está no escopo de teste.

Agradeço pela atenção.
