### ISSUE TITLE
Erro de timeout durante geração de carimbo de tempo

### ISSUE THREAD

**Issue by Filipy** [demoiselle/signer#404]
Boa tarde, ultimamente estamos tendo erros de timeout durante a geração de carimbo de tempo. já aconteceu anteriormente mas eram casos raros, mas atualmente tem acontecido com mais frequência, e estamos com dificuldade para identificar o motivo, segue os logs:

![image](https://github.com/demoiselle/signer/assets/22346052/7f1bc016-01c4-403c-915d-d5788432d5e6)

[aplicacao.log](https://github.com/demoiselle/signer/files/14601542/aplicacao.log)

**Comment by esaito** [comment]
Olá. 
Verifique se não tem firewall, proxy ou vpn, que possa estar bloqueando as requisições. 
Caso esteja tudo OK, abra um chamado neste link: https://form.omni.serpro.gov.br/upperScreenForm/3205
