### ISSUE TITLE
PDF Corrompido Apos Assinar

### ISSUE THREAD

**Issue by chrisengcomp** [demoiselle/signer#419]
Montei um programa para assinar um PDF. Ao executar não da nenhum erro e gera o arquivo pdf assinado, porem o PDF esta ficando corrompido.

Alguém tem alguma ideia do que pode ser?

Segue abaixo meu código:

        String pdfFilePath = "diretorio/arquivo.pdf";
        
        byte[] content = convertPDFToByteArray(pdfFilePath);
        
        String pfxFilePath = "diretorio/certificado.pfx";
        String pfxPassword = "*****";
        KeyStore ks = KeyStore.getInstance("PKCS12");
        FileInputStream fis = new FileInputStream(pfxFilePath);
        ks.load(fis, pfxPassword.toCharArray());
        fis.close();

        // Agora, exportar para .p12
        String p12FilePath = "diretorio/certificado.p12";
        FileOutputStream fos1 = new FileOutputStream(p12FilePath);
        ks.store(fos1, pfxPassword.toCharArray());
        fos1.close();

        String alias = "";
        Enumeration<String> aliases = ks.aliases();

        // Exibir todos os aliases encontrados no KeyStore
        while (aliases.hasMoreElements()) {
            alias = aliases.nextElement();
            System.out.println("Alias encontrado: " + alias);
        }
        PAdESSigner signer = new PAdESSigner();
        signer.setCertificates(ks.getCertificateChain(alias));
        signer.setPrivateKey((PrivateKey) ks.getKey(alias, pfxPassword.toCharArray()));
        signer.setSignaturePolicy(PolicyFactory.Policies.AD_RB_PADES_1_1);
        signer.setAlgorithm(SignerAlgorithmEnum.SHA512withRSA);
        byte[] signedPdfBytes = signer.doDetachedSign(content);

        // Caminho onde o arquivo PDF assinado será salvo
        String outputFilePath = "diretorio/arquivo_assinado.pdf";

        try {
            // Gerar o arquivo PDF a partir do array de bytes
            FileOutputStream fos = new FileOutputStream(outputFilePath);
            fos.write(signedPdfBytes);
            fos.close();
            
            System.out.println("PDF assinado gerado com sucesso em: " + outputFilePath);
        } catch (IOException e) {
            System.err.println("Erro ao gerar o arquivo PDF: " + e.getMessage());
        }

**Comment by esaito** [comment]
Para assinar em PDF é preciso manipular o PDF com alguma bibliteca específica. Temos um exemplo usando o PDFBox: 
https://github.com/demoiselle/signer/blob/master/policy-impl-pades/src/test/java/org/demoiselle/signer/policy/impl/pades/pkcs7/impl/PDFSignerTest.java

**Comment by chrisengcomp** [comment]
Ok, amigo. Consegui fazer funcionar corretamente a partir do exemplo.
Obrigado
