### ISSUE TITLE
Estudar instalador JNLP

### ISSUE THREAD

**Issue by juliancesar** [demoiselle/signer#56]
Estudar a utilização de JNLP para instalar o componente Desktop que levanta o WebSocket.

**Comment by joserenecampa** [comment]
https://docs.oracle.com/javase/tutorial/deployment/webstart/index.html

https://www.java.com/pt_BR/download/faq/java_webstart.xml

**Comment by juliancesar** [comment]
@joserenecampa, verificar se é possível colocar o jnlp/jar na inicialização do SO, caso contrario pode ser um impeditivo para utilização.

**Comment by juliancesar** [comment]
A principio o JNLP esta descartado por não permitir que seja adicionado o aplicativo na inicializaçao do SO.
