### ISSUE TITLE
Implementação de assinatura incorporada ao arquivo (Attached)

### ISSUE THREAD

**Issue by juliancesar** [demoiselle/signer#67]

**Comment by joserenecampa** [comment]
O componente já trata assinatura digital **atachada**, essa _issue_ trata algo mais específico?

**Comment by juliancesar** [comment]
Você esta correto. Esta issue pode ser fechada pois ela tratava questões relacionadas ao desktop.

Obrigado pela colaboração.

Julian Cesar

Enviado de um dispositivo móvel.
