### ISSUE TITLE
Cifragem de Decisfragem de Conteúdo

### ISSUE THREAD

**Issue by botelhojp** [demoiselle/signer#73]
Disponibilizar funcionalidade para cifrar e decifrar conteúdo, por meio de API de programação ou interface desktop utilizando a estratégia de criptografia simétrica para o conteúdo associada a criptografia assimétrica para a chave da criptografia simétrica.

**Comment by juliancesar** [comment]
Ficou decidido em reunião que por causa dos certificados geralmente criados pelo Serpro serem do tipo A e não permitir Decifragem com a chave privada vamos adotar a estratégia de possibilitar ao destinatário gerar uma par de chaves (pública e privada) e orientar que a chave pública seja enviada ao remetente para que ele gere o arquivo cifrado. Portanto a ferramenta Desktop deverá ter a opção de **Gerar Par de Chaves para Cifragem**.

**Comment by juliancesar** [comment]
Atividade foi migrada para outro repositório.
