### ISSUE TITLE
agent-desktop

### ISSUE THREAD

**Issue by Osdeni** [demoiselle/signer#77]
Ao rodar o agent-destktop com websocket sem ssl ele funciona normalmente, porém ao tentar fazer o uso com ssl (wss://localhost:9443) ele gera erros.

SO: ubuntu 14.04
Java: javac 1.8.0_121

**No chrome:**
`WebSocket connection to 'wss://localhost:9443/' failed: Error in connection establishment: net::ERR_INSECURE_RESPONSE`
`lib.min.js:1 Uncaught TypeError: Cannot read property 'hasCallbackError' of null
    at WebSocket.e.readyState.e.onerror (lib.min.js:1)`

**No console usando chrome:**
`XNIO-1 I/O-1, called closeInbound()
XNIO-1 I/O-1, fatal error: 80: Inbound closed before receiving peer's close_notify: possible truncation attack?
javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
%% Invalidated:  [Session-9, TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256]
XNIO-1 I/O-1, SEND TLSv1.2 ALERT:  fatal, description = internal_error
Padded plaintext before ENCRYPTION:  len = 2
0000: 02 50                                              .P
XNIO-1 I/O-1, WRITE: TLSv1.2 Alert, length = 26
XNIO-1 I/O-1, called closeOutbound()
XNIO-1 I/O-1, closeOutboundInternal()`

**No firefox:**
`Firefox can’t establish a connection to the server at wss://localhost:9443/.  lib.min.js:1:541`

**No console usando firefox:**
`XNIO-1 I/O-3, READ: TLSv1.2 Alert, length = 26
Padded plaintext after DECRYPTION:  len = 2
0000: 02 30                                              .0
XNIO-1 I/O-3, RECV TLSv1.2 ALERT:  fatal, unknown_ca
XNIO-1 I/O-3, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: unknown_ca
XNIO-1 I/O-3, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Received fatal alert: unknown_ca
XNIO-1 I/O-3, called closeInbound()
XNIO-1 I/O-3, fatal: engine already closed.  Rethrowing javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?
XNIO-1 I/O-3, called closeOutbound()
XNIO-1 I/O-3, closeOutboundInternal()
XNIO-1 I/O-3, SEND TLSv1.2 ALERT:  warning, description = close_notify
Padded plaintext before ENCRYPTION:  len = 2
0000: 01 00                                              ..
XNIO-1 I/O-3, WRITE: TLSv1.2 Alert, length = 26`

**Comment by juliancesar** [comment]
@Osdeni, esta funcionalidade não será mais desenvolvida no componente **Signer**, e estamos fazendo algumas provas de conceito internas para verificar a viabilidade desta funcionalidade devido a existirem problemas de segurança que podem inviabilizar ou dificultar muito a implementação, como você mesmo relatou.

A versão atual (SNAPSHOT) é composta pelos arquivos do link https://github.com/demoiselle/signer que já não possuem mais o Agent Desktop.
